# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ggol

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
namePrefix: ggol-

# Labels to add to all resources and selectors.
commonLabels:
  owner: tailoredshapes

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
- bases/backend/chunk/deployment.yaml
- bases/backend/chunk/service.yaml
- bases/backend/edge/deployment.yaml
- bases/backend/edge/service.yaml
- bases/backend/ingress.yaml


