apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /[0..2]/[0|2]/*
        backend:
          serviceName: worldedge
          servicePort: 4000
      - path: /[0|2]/1/*
        backend:
          serviceName: worldedge
          servicePort: 4000
      - path: /1/1/*
        backend:
          serviceName: worldchunck
          servicePort: 3000