apiVersion: v1
kind: Service
metadata:
  name: worldchunk
  labels:
    run: worldchunk
spec:
  type: NodePort
  selector:
    run: worldchunk
  ports:
  - port: 8080
    protocol: TCP
    name: http
    nodePort: 30001