kind: Deployment
apiVersion: apps/v1
metadata:
  name: worldchunk
  labels:
    run: worldchunk
spec:
  replicas: 1
  selector:
    matchLabels:
      run: worldchunk
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: worldchunk
    spec:
      containers:
        - name: chunk
          image: chunk
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}


